# -*- coding: utf-8 -*-
"""accuracy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvWZao1FFnpWIWCrcFcXYYRPfN79uY2p
"""

pip install scikit-learn

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import numpy as np

# Exemplo de valores reais e predições (substitua pelos seus dados)
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]   # rótulos reais
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]   # rótulos previstos pelo modelo

# Cálculo das métricas
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
conf_matrix = confusion_matrix(y_true, y_pred)

# Exibe os resultados
print("Matriz de Confusão:")
print(conf_matrix)
print("\nRelatório de Classificação:")
print(classification_report(y_true, y_pred))
print("Acurácia:", accuracy)
print("Precisão:", precision)
print("Recall:", recall)
print("F1-Score:", f1)