# -*- coding: utf-8 -*-
"""create_with_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvWZao1FFnpWIWCrcFcXYYRPfN79uY2p
"""

# prompt: create a dataframe that has midterm grades for 10 students

import pandas as pd
import numpy as np
# Create a list of 10 student names
students = [f'Student {i+1}' for i in range(10)]
# Generate random midterm grades between 50 and 100
midterm_grades = np.random.randint(50, 101, 10)
# Create the DataFrame
df = pd.DataFrame({'Student': students, 'Midterm Grade': midterm_grades})
# Print the DataFrame
df

# @title Midterm Grade

from matplotlib import pyplot as plt
df['Midterm Grade'].plot(kind='line', figsize=(8, 4), title='Midterm Grade')
plt.gca().spines[['top', 'right']].set_visible(False)

