# -*- coding: utf-8 -*-
"""GEE_model_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXx5Qfi3uP4HbKeNkHZsSxVnCsi978lY
"""

pip install statsmodels

import pandas as pd
import statsmodels.api as sm
from statsmodels.genmod.generalized_estimating_equations import GEE
from statsmodels.genmod.families import Binomial
from statsmodels.genmod.cov_struct import Exchangeable

# Exemplo de dados
data = pd.DataFrame({
    'subject': [1, 1, 2, 2, 3, 3],
    'time': [0, 1, 0, 1, 0, 1],
    'treatment': [0, 0, 1, 1, 1, 1],
    'response': [0, 1, 1, 1, 0, 1]
})

# Define as variáveis independentes (com constante) e a variável dependente
X = sm.add_constant(data[['treatment', 'time']])
y = data['response']

# Define a estrutura de correlação (ex: Exchangeable para medidas repetidas)
cov_struct = Exchangeable()

# Rodando o modelo GEE
model = GEE(y, X, groups=data['subject'], family=Binomial(), cov_struct=cov_struct)
result = model.fit()

# Exibe os resultados
print(result.summary())