# -*- coding: utf-8 -*-
"""llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/gupadovezi/16164634fa2a945173842d7636d5a728/llm.ipynb
"""

import requests
import json

API_KEY = "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"
MODEL_ID = "deepseek/deepseek-v3-base:free"  # Example model

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "HTTP-Referer": "https://openrouter.ai/deepseek/deepseek-v3-base:free",  # Optional for analytics
    "X-Title": "LLM",  # Optional for analytics
    "Content-Type": "application/json"
}

payload = {
    "model": MODEL_ID,
    "messages": [
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": "How can I treat scoliosis?."}
    ],
    "temperature": 0.7,
    "max_tokens": 1024,
    "stream": False,
    "top_p": 0.95
}

response = requests.post(
    "https://openrouter.ai/api/v1/chat/completions",
    headers=headers,
    data=json.dumps(payload)
)

print(response.json())

"""You are a helpful AI assistant"""