# -*- coding: utf-8 -*-
"""matplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Prag-7DFikkM_EuqaFpVvo7iDlMuatbV
"""

import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()