# -*- coding: utf-8 -*-
"""Modelo_Linear_Misto_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYefNFUpuldeD3BJsaTL_SGTYb4YTLlG
"""

pip install pandas statsmodels

import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import mixedlm

# Exemplo de dados
data = pd.DataFrame({
    'subject': [1, 1, 2, 2, 3, 3],
    'time': [0, 1, 0, 1, 0, 1],
    'treatment': [0, 0, 1, 1, 1, 1],
    'response': [5.0, 5.5, 6.0, 6.3, 4.8, 5.1]
})

# Modelo: resposta em função de tempo e tratamento, com intercepto aleatório por sujeito
model = mixedlm("response ~ treatment + time", data, groups=data["subject"])
result = model.fit()

# Resultado
print(result.summary())

mixedlm("response ~ treatment", data, groups=data["subject"], re_formula="~time")

pip install pingouin

import pandas as pd
import pingouin as pg

# Seus dados (mesmo exemplo anterior)
data = pd.DataFrame({
    'subject': [1, 1, 2, 2, 3, 3],
    'time': [0, 1, 0, 1, 0, 1],
    'treatment': [0, 0, 1, 1, 1, 1],
    'response': [5.0, 5.5, 6.0, 6.3, 4.8, 5.1]
})

# Ajuste do modelo
model = pg.mixed_anova(dv='response', within='time', between='treatment', subject='subject', data=data)

print(model)