# -*- coding: utf-8 -*-
"""print()_input().ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvWZao1FFnpWIWCrcFcXYYRPfN79uY2p
"""

nome = 'gustavo'
idade = 28
peso = 59
print(nome, idade, peso)

nome = input ('qual é o seu nome?')
idade = input ('quantos anos você tem?')
peso = input ('quanto você pesa?')
print(nome, idade, peso)

nome = input('Qual é seu Nome?')
print('Olá',nome,'!''Prazer em te conhecer!')

dia = input('Que dia você nasceu?')
mes = input('Que mês você nasceu?')
ano = input('Que ano você nasceu?')
print('Você nasceu no dia',dia,'de',mes,'de',ano)

primeiro_numero = input('Digite um numero')
segundo_numero = input('Digite outro numero')
print('A soma é', primeiro_numero + segundo_numero)